# Generated by Django 6.0.3 on 2026-04-13 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='project',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Proposal',
        ),
    ]
