# Generated by Django 6.0.3 on 2026-04-11 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0007_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_wallet', models.CharField(max_length=42)),
                ('freelancer_wallet', models.CharField(max_length=42)),
                ('amount_eth', models.DecimalField(decimal_places=8, max_digits=18)),
                ('status', models.CharField(choices=[('EMPTY', 'Empty'), ('FUNDED', 'Funded'), ('RELEASED', 'Released'), ('REFUNDED', 'Refunded'), ('DISPUTED', 'Disputed')], default='EMPTY', max_length=20)),
                ('tx_hash_funded', models.CharField(blank=True, max_length=66, null=True)),
                ('tx_hash_released', models.CharField(blank=True, max_length=66, null=True)),
                ('tx_hash_refunded', models.CharField(blank=True, max_length=66, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_as_client', to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_as_freelancer', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='projects.project')),
            ],
        ),
    ]
