# Generated by Django 6.0.3 on 2026-04-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowtransaction',
            name='client_wallet',
            field=models.CharField(blank=True, default='', max_length=42),
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='freelancer_wallet',
            field=models.CharField(blank=True, default='', max_length=42),
        ),
    ]
