# Generated by Django 6.0.3 on 2026-04-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='category',
            field=models.CharField(choices=[('web_development', 'Web Development'), ('data_science', 'Data Science'), ('ai_ml', 'AI & ML'), ('cloud_infra', 'Cloud Infra'), ('app_development', 'App Development'), ('networking', 'Networking'), ('graphic_design', 'Graphic Design'), ('cybersecurity', 'Cybersecurity')], default='web_development', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
