# Generated by Django 6.0.3 on 2026-04-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_freelancerprofile_category_user_email_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('not_available', 'Not Available')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='eth_wallet_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='languages',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
