# Generated by Django 6.0.3 on 2026-04-13 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('PROPOSAL', 'New Proposal'), ('ACCEPTED', 'Proposal Accepted'), ('REJECTED', 'Proposal Rejected'), ('FUNDED', 'Escrow Funded'), ('RELEASED', 'Payment Released'), ('DISPUTED', 'Dispute Raised'), ('MESSAGE', 'New Message'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('related_proposal_id', models.IntegerField(blank=True, null=True)),
                ('related_project_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
