# Generated by Django 6.0.3 on 2026-04-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('PROPOSAL', 'New Proposal'), ('ACCEPTED', 'Proposal Accepted'), ('REJECTED', 'Proposal Rejected'), ('FUNDED', 'Escrow Funded'), ('RELEASED', 'Payment Released'), ('COMPLETED', 'Project Completed'), ('DISPUTED', 'Dispute Raised'), ('MESSAGE', 'New Message'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
    ]
